name: Docker

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        id: login-docker-hun
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: setup-docker-buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup UV including caching
        id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.6.16"
          enable-cache: true

      - name: Build and push
        id: docker-build-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: afaulconbridge/camvidlog2:latest
          cache-from: type=registry,ref=afaulconbridge/camvidlog2:latest
          cache-to: type=inline
