name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Setup UV including caching
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.16"
          enable-cache: true

      - name: Setup Python
        id: setup-python
        run: uv python install

      - name: Setup python dependencies
        id: setup-deps
        run: uv sync --locked --all-extras --dev

      - name: Setup apt dependencies
        id: setup-deps-extra
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg
        # ideally want to cache this, and all its dependencies!

      - name: Cache go2rtc binary
        # will automatically cache at end of process
        id: cache-go2rtc
        uses: actions/cache@v4
        with:
          path: ./go2rtc
          key: go2rtc-v1-v1.9.9-${{runner.os}}-${{runner.arch}}

      - name: Download go2rtc if not cached
        if: steps.cache-go2rtc.outputs.cache-hit != 'true'
        run: |
          wget -O ./go2rtc https://github.com/AlexxIT/go2rtc/releases/download/v1.9.9/go2rtc_linux_amd64
          chmod +x ./go2rtc

      - name: Cache yoloe-11l-seg.onnx
        id: cache-onnx
        uses: actions/cache@v4
        with:
          path: yoloe-11l-seg.onnx
          key: yoloe-11l-seg-onnx-v1-${{ runner.os }}-${{ runner.arch }}

      - name: Prepare YOLOE ONNX model if not cached
        if: steps.cache-onnx.outputs.cache-hit != 'true'
        run: |
          uv run python bin/prepare-yoloe.py \
            -c "deer" -c "bird" -c "hedgehog" -c "otter" -c "giraffe" \
            --batch 10 \
            --force

      - name: Run pytest
        id: pytest
        run: uv run pytest test
