name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup UV including caching
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.16"
          enable-cache: true

      - name: Setup Python
        id: setup-python
        run: uv python install

      - name: Setup dependencies
        id: setup-deps
        run: uv sync --locked --all-extras --dev

      - name: Setup extra dependencies
        id: setup-deps-extra
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ffmpeg
          version: 1.0

      - name: Cache go2rtc binary
        # will automatically cache at end of process
        id: cache-go2rtc
        uses: actions/cache@v4
        with:
          path: ./
          key: go2rtc-v1.9.9-${{runner.os}}-${{runner.arch}}

      - name: Download go2rtc if not cached
        if: steps.cache-go2rtc.outputs.cache-hit != 'true'
        run: |
          wget -O ./go2rtc https://github.com/AlexxIT/go2rtc/releases/download/v1.9.9/go2rtc_linux_amd64
          chmod +x ./go2rtc

      - name: Run pytest
        id: pytest
        run: uv run pytest test
