name: test

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup UV including caching
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.16"
          enable-cache: true

      - name: Setup Python
        id: setup-python
        run: uv python install

      - name: Setup dependencies
        id: setup-deps
        run: uv sync --locked --all-extras --dev

      - name: Run pytest
        id: pytest
        run: uv run pytest test
